<?xml version="1.0"?>
<package format="2">
  <name>chris_planner</name>
  <version>2.0.0</version>
  <description>C++ ROS wrapper for chris_planner path planning algorithm</description>

  <maintainer email="sa-vm@todo.todo">sa-vm</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>roslib</build_depend>
  <build_depend>libyaml-cpp-dev</build_depend>

  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>roslib</build_export_depend>

  <exec_depend>roscpp</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>roslib</exec_depend>
  <exec_depend>libyaml-cpp-dev</exec_depend>

  <export>
  </export>
</package>
